// - LOGIN
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGIN_ERROR = "LOGIN_ERROR";

export const LOGIN = "LOGIN";
export const LOGIN_START = "LOGIN_START";


// - LOGOUT
export const LOGOUT ="LOGOUT"


// - USER
export const SET_CURRENT_USER_DETAILS = "SET_CURRENT_USER_DETAILS"
export const SET_UNSEEN_MESSAGES_COUNT = "SET_UNSEEN_MESSAGES_COUNT"
export const EDIT_CURRENT_USER_DETAILS = "EDIT_CURRENT_USER_DETAILS"
export const SET_MESSAGE_NOTIFICATION_COUNT = "SET_MESSAGE_NOTIFICATION_COUNT"

//APPLICATION
export const CHANGE_THEME = "CHANGE_THEME";
export const CHANGE_FONT = "CHANGE_FONT";
export const FORCE_APPEARANCE = "FORCE_APPEARANCE";
export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
export const SET_MENU = "SET_MENU";
export const SET_INTRO = "SET_INTRO";

//NOTIFICATION
export const NOTIFICATION_COUNT = "NOTIFICATION_COUNT"

//EXPO TOKEN
export const SET_EXPO_TOKEN = "SET_EXPO_TOKEN"