# Generated by Django 3.2.9 on 2021-11-13 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatapp', '0003_auto_20211113_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='membermessages',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='membermessages',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
