# Generated by Django 3.2.9 on 2021-12-28 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatapp', '0005_auto_20211116_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermessages',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_reciever', to=settings.AUTH_USER_MODEL),
        ),
    ]
