# Generated by Django 3.2.9 on 2022-01-04 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatapp', '0007_auto_20220104_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membermessages',
            options={'ordering': ('timestamp',)},
        ),
        migrations.RemoveField(
            model_name='membermessages',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='membermessages',
            name='recipient',
        ),
        migrations.AddField(
            model_name='membermessages',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_reciever', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
