# Generated by Django 3.2.9 on 2022-01-04 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0008_auto_20220104_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membermessages',
            old_name='receiver',
            new_name='reciever',
        ),
    ]
