# Generated by Django 3.2.9 on 2022-01-04 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatapp', '0009_rename_receiver_membermessages_reciever'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermessages',
            name='reciever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_reciever', related_query_name='r', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='membermessages',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_author', related_query_name='s', to=settings.AUTH_USER_MODEL),
        ),
    ]
