# Generated by Django 3.2.9 on 2022-01-05 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0010_auto_20220104_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membermessages',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.RemoveField(
            model_name='membermessages',
            name='room_name',
        ),
    ]
