# Generated by Django 3.2.9 on 2021-12-31 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inspectionapp', '0022_alter_files_type'),
        ('Notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='areas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notification_area', to='Inspectionapp.entity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notifications',
            name='entity',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='notification_entity', to='Inspectionapp.entity'),
            preserve_default=False,
        ),
    ]
