# Generated by Django 3.2.9 on 2021-12-31 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inspectionapp', '0022_alter_files_type'),
        ('Notifications', '0002_auto_20211231_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='areas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_area', to='Inspectionapp.areas'),
        ),
    ]
