# Generated by Django 3.2.9 on 2021-12-31 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0004_remove_notifications_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='areas',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='entity',
        ),
    ]
