# Generated by Django 3.2.9 on 2022-01-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0005_auto_20211231_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='title',
            field=models.CharField(default='1', max_length=300),
            preserve_default=False,
        ),
    ]
