# Generated by Django 3.2.9 on 2022-01-05 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_profile_messenger_list'),
        ('Notifications', '0006_notifications_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_sender', to='accounts.profile'),
        ),
    ]
