# Generated by Django 3.2.9 on 2021-11-22 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Inspectionapp', '0016_areas_entity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=500, null=True)),
                ('profile_image', models.ImageField(upload_to='profiles')),
                ('active_on_service', models.BooleanField(default=True)),
                ('office_contact', models.IntegerField(blank=True, null=True)),
                ('manager_contact', models.IntegerField(blank=True, null=True)),
                ('area_allocated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inspectionapp.areas')),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inspectionapp.entity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
