# Generated by Django 3.2.9 on 2021-11-22 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inspectionapp', '0017_auto_20211122_1941'),
        ('accounts', '0002_auto_20211122_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspector',
            name='area_allocated',
            field=models.ManyToManyField(blank=True, to='Inspectionapp.Areas'),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspector_user', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='inspector_allocated',
            field=models.ManyToManyField(blank=True, to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('INSPECTOR', 'INSPECTOR'), ('MANAGER', 'MANAGER'), ('ADMIN', 'ADMIN')], max_length=100),
        ),
    ]
