# Generated by Django 3.2.9 on 2021-11-22 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20211122_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspector',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspector_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
