# Generated by Django 3.2.9 on 2021-11-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_un_seen_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='task_reassigned',
            field=models.IntegerField(default=0),
        ),
    ]
