# Generated by Django 3.2.9 on 2021-11-26 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_task_reassigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='task_reassigned',
        ),
    ]
