# Generated by Django 3.2.9 on 2021-11-28 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_profile_task_reassigned'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
