# Generated by Django 3.2.9 on 2022-01-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_delete_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpoToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='expo_token',
            field=models.ManyToManyField(to='accounts.ExpoToken'),
        ),
    ]
