# Generated by Django 3.2.9 on 2022-01-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220101_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expotoken',
            name='token',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
