# Generated by Django 3.2.9 on 2022-01-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_expotoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notfication_count',
            field=models.IntegerField(default=0),
        ),
    ]
