# Generated by Django 3.2.9 on 2022-01-02 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_profile_notfication_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='notfication_count',
            new_name='notification_count',
        ),
    ]
