# Generated by Django 4.0.1 on 2022-01-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20220106_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expo_token',
            field=models.ManyToManyField(blank=True, to='accounts.ExpoToken'),
        ),
    ]
