# Generated by Django 3.2.9 on 2021-11-19 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Inspectionapp', '0003_entity_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entitymembers',
            name='email',
        ),
        migrations.RemoveField(
            model_name='entitymembers',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='entitymembers',
            name='manager_contact',
        ),
        migrations.RemoveField(
            model_name='entitymembers',
            name='name',
        ),
        migrations.RemoveField(
            model_name='entitymembers',
            name='office_contact',
        ),
        migrations.RemoveField(
            model_name='entitymembers',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='entitymembers',
            name='position',
        ),
        migrations.CreateModel(
            name='TaskAssigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('RESOLVED', 'RESOLVED'), ('NEW', 'NEW'), ('PROCESSING', 'PROCESSING')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('priority', models.CharField(choices=[('URGENT', 'URGENT'), ('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], max_length=50)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignedTo', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignedBy', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inspectionapp.entity')),
            ],
        ),
    ]
