# Generated by Django 3.2.9 on 2021-11-19 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inspectionapp', '0004_auto_20211119_0823'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EntityMembers',
        ),
    ]
