# Generated by Django 3.2.9 on 2021-11-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspectionapp', '0006_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('PROCESSING', 'PROCESSING'), ('NEW', 'NEW')], default='NEW', max_length=50),
        ),
    ]
