# Generated by Django 3.2.9 on 2021-11-19 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inspectionapp', '0008_auto_20211119_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inspectionapp.taskassigned')),
            ],
        ),
    ]
