# Generated by Django 3.2.9 on 2021-11-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspectionapp', '0009_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='type',
            field=models.CharField(default='aa', max_length=100),
            preserve_default=False,
        ),
    ]
