# Generated by Django 3.2.9 on 2021-11-20 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inspectionapp', '0011_auto_20211120_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='person_in_charge',
        ),
    ]
