# Generated by Django 3.2.9 on 2021-11-20 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Inspectionapp', '0012_auto_20211120_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='background_image',
            field=models.ImageField(default='2', upload_to='entity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entity',
            name='description',
            field=models.TextField(default='aaa', help_text='small description about entity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entity',
            name='person_in_charge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
