# Generated by Django 3.2.9 on 2021-11-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspectionapp', '0013_auto_20211120_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='motto',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
