# Generated by Django 3.2.9 on 2021-11-20 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inspectionapp', '0015_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='areas',
            name='entity',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Inspectionapp.entity'),
            preserve_default=False,
        ),
    ]
