# Generated by Django 3.2.9 on 2021-11-22 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inspectionapp', '0016_areas_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='active',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='motto',
        ),
    ]
