# Generated by Django 3.2.9 on 2021-11-23 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inspectionapp', '0017_auto_20211122_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areas',
            name='entity',
        ),
    ]
