# Generated by Django 3.2.9 on 2021-11-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspectionapp', '0018_remove_areas_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='areas',
            field=models.ManyToManyField(blank=True, to='Inspectionapp.Areas'),
        ),
    ]
