# Generated by Django 3.2.9 on 2021-11-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspectionapp', '0019_entity_areas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassigned',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('NEW', 'NEW'), ('RE-ASSIGNED', 'RE-ASSIGNED'), ('ISSUE', 'ISSUE'), ('PROCESSING', 'PROCESSING')], default='NEW', max_length=50),
        ),
    ]
