# Generated by Django 3.2.9 on 2021-11-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inspectionapp', '0020_alter_taskassigned_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassigned',
            name='reason_for_reassigning',
            field=models.TextField(blank=True),
        ),
    ]
