# Generated by Django 4.0.1 on 2022-01-09 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inspectionapp', '0022_alter_files_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='type',
        ),
    ]
